services:
  backend:
    build: ./server
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  db:
    image: mysql:8
    container_name: expense-tracker-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3308:3307"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
